import type { ThemeConfig } from "antd";
import { colors } from "./theme.colors";

export const theme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorInfo: colors.primary,
    colorBgBase: colors.backgroundBase,
    colorBgLayout: colors.backgroundBase,
    colorBgContainer: colors.surface,
    colorBgElevated: colors.backgroundElevated,
    colorBgSpotlight: colors.backgroundSpotlight,
    colorText: colors.textPrimary,
    colorTextSecondary: colors.textSecondary,
    colorTextTertiary: colors.textTertiary,
    colorTextQuaternary: colors.textQuaternary,
    colorBorder: colors.borderDefault,
    colorBorderSecondary: colors.borderSubtle,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    borderRadius: 8,
    borderRadiusSM: 6,
    borderRadiusLG: 12,
    controlHeight: 38,
    controlHeightSM: 30,
    controlHeightLG: 44,
    fontSize: 14,
  },
  components: {
    Button: {
      colorPrimary: colors.primary,
      colorPrimaryHover: colors.primaryHover,
      colorPrimaryActive: colors.primaryActive,
      colorPrimaryBg: colors.backgroundPrimary,
      colorPrimaryBgHover: colors.backgroundPrimaryHover,
      borderRadius: 8,
    },
    Input: {
      colorBgContainer: colors.surface,
      colorBorder: colors.borderDefault,
      hoverBorderColor: colors.primaryFocus,
      activeBorderColor: colors.primary,
      activeShadow: colors.primaryFocusShadow,
    },
    Select: {
      colorBgContainer: colors.surface,
      colorBorder: colors.borderDefault,
      optionSelectedBg: colors.backgroundActive,
      optionActiveBg: colors.backgroundPrimary,
      optionSelectedColor: colors.textAccent,
      hoverBorderColor: colors.primaryFocus,
      activeBorderColor: colors.primary,
    },
    Segmented: {
      trackBg: colors.backgroundElevated,
      itemColor: colors.textSecondary,
      itemHoverColor: colors.textPrimary,
      itemHoverBg: colors.backgroundHover,
      itemActiveBg: colors.primaryActive,
      itemSelectedBg: colors.primary,
      itemSelectedColor: colors.white,
    },
    Table: {
      colorBgContainer: colors.surface,
      headerBg: colors.backgroundElevated,
      headerColor: colors.textPrimary,
      rowHoverBg: colors.backgroundHover,
      borderColor: colors.borderDefault,
      headerSplitColor: colors.borderDefault,
    },
    Card: {
      colorBgContainer: colors.surface,
      colorBorderSecondary: colors.borderDefault,
      borderRadiusLG: 12,
    },
    Modal: {
      contentBg: colors.surface,
      headerBg: colors.surface,
      footerBg: colors.surface,
      titleColor: colors.textPrimary,
    },
    Menu: {
      itemBg: "transparent",
      itemHoverBg: colors.backgroundElevated,
      itemSelectedBg: colors.backgroundActive,
      itemSelectedColor: colors.primaryHover,
      itemColor: colors.textSecondary,
      itemHoverColor: colors.textPrimary,
      darkItemBg: "transparent",
      darkSubMenuItemBg: colors.surface,
      darkItemSelectedBg: colors.backgroundActive,
      darkItemSelectedColor: colors.primaryHover,
      darkItemColor: colors.textSecondary,
      darkItemHoverColor: colors.textPrimary,
    },
    Tabs: {
      itemColor: colors.textTertiary,
      itemHoverColor: colors.primaryHover,
      itemSelectedColor: colors.primaryHover,
      inkBarColor: colors.primary,
    },
    Tag: { defaultBg: colors.backgroundTag, defaultColor: colors.primaryHover },
    Checkbox: { colorPrimary: colors.primary, colorPrimaryHover: colors.primaryHover },
    Radio: { colorPrimary: colors.primary, colorPrimaryHover: colors.primaryHover },
    Layout: {
      colorPrimary: colors.primary,
      colorPrimaryHover: colors.primaryHover,
      bodyBg: colors.backgroundBase,
      headerBg: colors.surface,
      footerBg: colors.backgroundBase,
      siderBg: colors.backgroundBase,
    },
    Switch: { colorPrimary: colors.primary, colorPrimaryHover: colors.primaryHover },
    Pagination: { itemActiveBg: colors.backgroundActive, itemActiveColor: colors.primaryHover },
  },
};
